export const INCREASE_BALANCE = "INCREASE_BALANCE";
export const DECREASSE_BALANCE = "DECREASSE_BALANCE";
export const BUY_BUSINESS = "BUY_BUSINESS";
export const INCREASE_PROFIT = "INCREASE_PROFIT";
export const HIRE_MANAGER = "HIRE_MANAGER";
